name: SimpleShop
main: Limbo.SimpleShop
author: Limbo48
version: 1.0
api-version: 1.18
softdepend: [ItemsAdder, Citizens]
depend: [Vault]

commands:
  simpleshop:
    description: Open Shop
    aliases: [ss, shop]
  sreload:
    description: Reload config
  transfer:
    description: Give money to player
    aliases: [tf, givemoney, bank]

permissions:
  shop.admin:
    default: false
    children:
      shop.sell: true
      shop.trade: true
      shop.shop: true
      shop.transfer: true
      shop.bypass: true
  shop.shop:
    default: op
  shop.sell:
    default: op
  shop.trade:
    default: op
  shop.transfer:
    default: true
  shop.bypass:
    default: false